#pragma once
enum TEXTYPE { TEX_SINGLE, TEX_MULTI };
enum OBJECT_ID {OBJECT_ID_PLAYER, OBJECT_ID_NPC, OBJECT_ID_TERRAIN, OBJECT_ID_MONSTER,OBJECT_LOGO, OBJECT_ID_END  };
enum LAYER_ID {LAYER_ID_1, LAYER_ID_2, LAYER_ID_3, LAYER_ID_4, LAYER_ID_5, LAYER_ID_END};
enum SCENE_ID { SCENE_ID_LOGO, SCENE_ID_MENU, SCENE_ID_STAGE, SCENE_ID_DONGKU, SCENE_ID_HAYOON, SCENE_ID_END };
enum DIR_ID {DIR_ID_FORWORD, DIR_ID_BACK, DIR_ID_LEFT, DIR_ID_RIGHT, DIR_ID_END};